image: aergus/latex

stages:
  - build

build:
  stage: build

  script:
    - mkdir output
    - shell_escape=t latexmk -pdf -jobname=./output/build main.tex;
    - cp output/build.pdf main.pdf

  artifacts:
    paths:
      - main.pdf

